services:
  app:
    build:
      args:
        user: joao
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-bookstore:latest
    container_name: my-laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - my-laravel-rede
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: my-laravel-db
    restart: unless-stopped
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      - my-laravel-rede
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: my-laravel-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - my-laravel-rede

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - 8800:80
    networks:
      - my-laravel-rede

networks:
  my-laravel-rede:
    driver: bridge

volumes:
  db_data:
